<?php include __DIR__ . "/../_header.phtml"; ?>
<div class="d-flex justify-content-between align-items-center mb-3">
    <?php if (Utils_Login::is_admin()): ?>
        <a href="/geneData/GeneDataItem"  class="btn btn-outline-success rounded-pill px-3">
            Gene Table
        </a>
        <a href="/geneData/Admin/users"  class="btn btn-outline-success rounded-pill px-3">
            Add User
        </a>
    <?php endif; ?>
</div>

<?php if (!Utils_Login::is_admin()) {
    header("Location: /geneData/Login");
    exit();
}
?>

<?php /** @var Domains_User $data */ ?>
<?php if($data) { ?>
    <table class="gene-data-table table table-striped table-hover table-bordered">
        <thead class="table-dark">
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Admin</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($data as $obj){ ?>
            <tr>
                <td class="fw-semibold"><?=$obj->id?></td>
                <td><?=$obj->username?></td>
                <td><?=$obj->is_admin?></td>
                <td><button onclick="delete_user(<?=$obj->id?>)" class="btn btn-danger">Delete</button></td>
            </tr>
            <?php
        }
        ?>
        </tbody>
    </table>
<?php } else { ?>
    <div class="p-4 text-center">
        <div class="alert alert-info mb-0">
            No data found.
        </div>
    </div>
<?php } ?>

<script>
    function delete_user(id){
        fetch("./Admin/users/" + id, {
            method: "DELETE"
        }).then(() => location.reload());
    }
</script>

<?php include __DIR__ . "/../_footer.phtml"; ?>
